version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mariadb
    depends_on:
      - mariadb
    restart: always

volumes:
  mariadb_data:
