version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mariadb
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_data:
  wordpress_data:
